# Generated by Django 5.1.1 on 2024-10-09 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('tax_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_advisor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
