# Generated by Django 5.1.1 on 2024-10-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_confirmed_alter_appointment_tax_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
