# Generated by Django 5.1.1 on 2024-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointment_user_request_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='online', max_length=10),
        ),
    ]
