# Generated by Django 5.0.9 on 2024-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_surchargerate_taxscheme_remove_userdetails_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='incometype',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
