# Generated by Django 5.0.9 on 2024-10-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_userdetails_incometype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_regime_tax', models.FloatField()),
                ('new_regime_tax', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.userdetails')),
            ],
        ),
    ]
