# Generated by Django 5.0.9 on 2024-10-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_taxcalculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
    ]
