# Generated by Django 5.1.1 on 2024-10-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
        ('calculator', '0010_taxcalculator_remove_userdetails_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculation',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userdetails'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
