# Generated by Django 5.1.1 on 2024-10-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_taxcalculation_user_details_delete_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculator',
            name='regime',
        ),
    ]
