# Generated by Django 5.1.1 on 2024-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_remove_taxcalculator_regime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='user_details',
        ),
        migrations.AddField(
            model_name='taxcalculator',
            name='age_group',
            field=models.CharField(choices=[('below_60', 'Below_60'), ('senior', '60 to 80'), ('super_senior', 'Above 80')], max_length=12, null=True, verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='taxcalculator',
            name='income_type',
            field=models.CharField(choices=[('salarised', 'Salarised'), ('business', 'Business')], max_length=10, null=True, verbose_name='Income Type'),
        ),
        migrations.AddField(
            model_name='taxcalculator',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Income after Expenses'),
        ),
        migrations.AddField(
            model_name='taxcalculator',
            name='regime',
            field=models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], max_length=10, null=True, verbose_name='Tax Regime'),
        ),
        migrations.AddField(
            model_name='taxcalculator',
            name='total_income',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Income'),
        ),
        migrations.AlterField(
            model_name='taxcalculator',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deductions'),
        ),
        migrations.AlterField(
            model_name='taxcalculator',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Income'),
        ),
    ]
