# Generated by Django 5.1.1 on 2024-10-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_remove_taxcalculation_user_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculator',
            name='regime',
        ),
    ]
