# Generated by Django 5.1.1 on 2024-11-05 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_userinput_delete_taxcalculator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaxResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_regime_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_regime_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_regime', models.CharField(max_length=20)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='calculator.userinput')),
            ],
        ),
    ]
