# Generated by Django 5.1.1 on 2024-11-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_userinput_user_taxresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxresults',
            name='calculated_at',
        ),
    ]
