# Generated by Django 5.1.1 on 2024-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_remove_taxresults_calculated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='deduction_80c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='deduction_80ccd1b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='deduction_80d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='deduction_80e',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='deduction_80eea',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='deduction_80g',
            field=models.FloatField(default=0),
        ),
    ]
