# Generated by Django 5.1.1 on 2024-10-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_alter_userrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
