# Generated by Django 5.1.1 on 2024-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_taxadvisorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
