# Generated by Django 5.0.9 on 2024-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_userrequest_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxadvisorprofile',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
        ),
    ]
