# Generated by Django 5.1.1 on 2024-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0007_alter_taxadvisorprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxadvisorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('not_specified', 'Prefer not to specify')], default='Not specified', max_length=30),
        ),
    ]
