# Generated by Django 5.0.9 on 2024-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_alter_taxadvisorprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxadvisorprofile',
            name='clients_attended_successfully',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxadvisorprofile',
            name='clients_currently_attending',
            field=models.IntegerField(default=0),
        ),
    ]
