# Generated by Django 5.1.1 on 2024-10-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
        ('calculator', '0013_remove_taxcalculation_user_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
